### ISSUE TITLE
Update this documentation

### ISSUE THREAD

**Issue by tommyhaggerty** [Oteemo/charts#100]
https://github.com/Oteemo/charts/blob/629c93fe78671a61bb759807ab95f5a8c7b6d70f/charts/sonarqube/values.yaml#L187

Hi,

This line should read 
`# postgresqlServer: ""` 
rather than 
`# postgresServer: ""`

Thanks!

**Comment by rjkernick** [comment]
Documentation seems to be updated on the master branch and most recent release. Let me know if you need anything else.
