### ISSUE TITLE
[sonarqube] sonarqube 8.3 results in crashloop

### ISSUE THREAD

**Issue by n2aws** [Oteemo/charts#103]
Using the chart for sonarqube 8.2-developer works as expected. However when trying 8.3-developer, it results in the following error:

```
sonarqube /opt/sonarqube/bin/run.sh: line 13: 1: unbound variable
sonarqube stream closed
```

Running the docker container via `docker run sonarqube:8.3-developer` appears to work as expected, so I suspect that this may be an incompatibility between the chart itself,  and the recent change in SonarSource/docker-sonarqube in using the alpine-jdk base image.

I see that the helm chart has several settings in the values.yml for overiding images at https://github.com/Oteemo/charts/blob/master/charts/sonarqube/values.yaml#L169-L174 but I've yet to find the magic incantation to make this work.

Worth noting, this issue is also documented at https://github.com/SonarSource/docker-sonarqube/issues/401

**Comment by p0bailey** [comment]
Same error with me.

**Comment by n2aws** [comment]
This issue was resolved upstream in github.com/SoanrSource/docker-sonarqube#401

**Comment by p0bailey** [comment]
Yes, I can confirm that works as expected.

Phillip
