### ISSUE TITLE
[sonarqube]: Postgresql password is never set when using an external database

### ISSUE THREAD

**Issue by hoepfnerj** [Oteemo/charts#131]
I am using the sonarqube chart and there seems to be a problem with external postgresql databases. The environment variable `SONARQUBE_JDBC_PASSWORD` seems to never be set when `postgresql.enabled=false`.

In `deployment.yaml` line 166:
`{{- if or .Values.postgresql.enabled .Values.postgresql.existingSecret }}`

In `secret.yaml` line 1 and 2:
```
{{- if eq .Values.postgresql.enabled false -}}
{{- if not .Values.postgresql.existingSecret -}}
```
This seems to be mutually exclusive?
See ab8fd3d85e7864308f2302bd579933d78676680b

**Comment by marvin-w** [comment]
I was also running in this issue today, glad someone is already taking care of it!

My workaround was to go back to Chart version 6.2.2 and then it was running smoothly.

**Comment by hoepfnerj** [comment]
Thank you!
