### ISSUE TITLE
charts/sonarqube: install-plugins.yaml w/o http/https proxy

### ISSUE THREAD

**Issue by alex1989hu** [Oteemo/charts#14]
**ISSUE**:
If you deploy `sonarqube` behind corporate MITM proxy it is impossible to download any plugins due to lack of customizable proxy environment variables in [deployment.yaml#L103](https://github.com/Oteemo/charts/blob/master/charts/sonarqube/templates/deployment.yaml#L103). 

Thus [wget](https://github.com/Oteemo/charts/blob/master/charts/sonarqube/templates/install-plugins.yaml#16) is not able to resolve target host, therefore **install-plugins** `initContainer` silently fails without no plugin download.

**NOTE**:
After locally applied `env` for **install-plugins** `initContainer` I found that `alpine:3.10.3` provided wget is not able to handle more than 5 redirections and it fails with: `Too many redirects`.

**Comment by rjkernick** [comment]
Can you try to use --set plugins.initContainerImage="rjkernick/alpine-wget:latest" ?  I found some people having issues with the light wget installed by default. That container just has the full wget installed. Let me know if that works and I'll keep investigating if it doesn't. I don't have a corporate firewall to test against.

**Comment by alex1989hu** [comment]
> Can you try to use --set plugins.initContainerImage="rjkernick/alpine-wget:latest" ? I found some people having issues with the light wget installed by default. That container just has the full wget installed. Let me know if that works and I'll keep investigating if it doesn't. I don't have a corporate firewall to test against.

`rjkernick/alpine-wget:latest` works! 🎉

FYI: it was enough to locally start container from CLI e.g. `docker run -it --rm rjkernick/alpine-wget:latest /bin/sh`, export http_proxy;https_proxy and call `wget`

**Comment by rjkernick** [comment]
Awesome. So now you just need the ability to pass http_proxy and https_proxy into the init container right? I can probably try and add that functionality

**Comment by alex1989hu** [comment]
If the image will be part of the Helm chart, then yes. It is enough to add possibility to end-users to provide proxy environment variables in [deployment.yaml#L103](https://github.com/Oteemo/charts/blob/master/charts/sonarqube/templates/deployment.yaml#L103). 
One more important thing: neither your, nor the original image does not repect capital `HTTP_PROXY` / `HTTPS_PROXY`. Instead of capital letters, we shall use lowercase e.g. `http_proxy`.

**Comment by rjkernick** [comment]
Thanks. I'll try and get that into the chart in the next couple days.

**Comment by usmonster** [comment]
Hello! Can we prefer to use curl instead of wget (as suggested in helm/charts#18805)? This would allow us to keep the trusted official source as the default, and then you wouldn't have to maintain this one-off image. What do you think?

Thanks for the fix!

**Comment by alex1989hu** [comment]
> Hello! Can we prefer to use curl instead of wget (as suggested in [helm/charts#18805](https://github.com/helm/charts/issues/18805))? This would allow us to keep the trusted official source as the default, and then you wouldn't have to maintain this one-off image. What do you think?
> 
> Thanks for the fix!

**From the PR:**
@usmonster you are absolutely right. It is going to be tricky:  alpine:3.10.3 -> `/bin/sh: curl: not found`
