### ISSUE TITLE
Charts doesn't honor namespaces.

### ISSUE THREAD

**Issue by abhilashjoseph** [Oteemo/charts#141]
The nexus chart that I was trying to use did not have the template definitions to set the namespace properties. I have a pull request ready to be pushed. Please provide me access or if there is an alternate option to send a PR please let me know

**Comment by rjkernick** [comment]
Hello, the typical flow would be to create a fork of the repo, push your changes there, and then create a cross-fork PR against this repo. Let me know if you need any other assistance.

**Comment by abhilashjoseph** [comment]
> Hello, the typical flow would be to create a fork of the repo, push your changes there, and then create a cross-fork PR against this repo. Let me know if you need any other assistance.

Sure thank you, will do that!

**Comment by abhilashjoseph** [comment]
I have submitted a PR for the changes!
