### ISSUE TITLE
[sonatype-nexus] update image to 3.25 to resolve nuget issues

### ISSUE THREAD

**Issue by h-c-a** [Oteemo/charts#147]
Nexus now has better support to nuget, help with proving a new image (3.25)

https://help.sonatype.com/repomanager3/release-notes#ReleaseNotes-NewandNoteworthy

**Comment by rjkernick** [comment]
Since we are currently using the TravelAudience docker image, we have to wait for https://github.com/travelaudience/docker-nexus/pull/48 to be merged
