### ISSUE TITLE
sonarqube: /opt/sq/bin/run.sh: No such file or directory on version 8.2-community

### ISSUE THREAD

**Issue by rnkhouse** [Oteemo/charts#15]
When I install sonarqube version `8.2-community` I am getting bellow error:

    /tmp/scripts/copy_plugins.sh: line 14: /opt/sq/bin/run.sh: No such file or directory

Helm command:

    helm install oteemocharts/sonarqube --name sonarqube \
    --set image.tag="8.2-community" \
    --set sonarqubeFolder="/opt/sq" \
    --set postgresql.enabled=true

Checked helm list:

    sonarqube     	1       	Mon Mar  2 16:14:25 2020	DEPLOYED	sonarqube-4.0.0     	7.9.2      	default

Even after defining the 8.2-community version during installation, it's installing 7.9.2 version.

**Comment by devtribe** [comment]
Also happens with `8.2-developer`

**Comment by devtribe** [comment]
you need to remove `--set sonarqubeFolder="/opt/sq" \`
They have changed the folder back to pre `8` default path.

**Comment by rjkernick** [comment]
I'll update it this morning. Thanks for letting me know.

**Comment by rjkernick** [comment]
"helm ls" is going to show the version that is in chart.yaml. If you describe the pod, it deploys the version you specify in the override. I will work on getting the chart updated to 8.2 today and modify the path to reflect the latest changes.

**Comment by rnkhouse** [comment]
@rjkernick Actually, app version should be taken from the `image.tag` variable. Right now it's hardcoded.

**Comment by rjkernick** [comment]
Chart.yaml cannot be templated, so it will always be hardcoded to the appVersion there. I'm not finding any example where this is not the case.
