### ISSUE TITLE
nexus backup persistentVolumeClaim gets created even when nexusBackup.enabled is false

### ISSUE THREAD

**Issue by Skaronator** [Oteemo/charts#158]
I'm currently trying to install the nexus helm chart with a already existing claim but the pod will not start since it is requesting a existing claimName for the nexusBackup Mount.

Quick search in the code: This part always add a `persistentVolumeClaim` when the `nexusBackup.persistence.enabled` variable is `true`...

https://github.com/Oteemo/charts/blob/c28c76fbb53173aee9014c4b990a771a9ff5bea9/charts/sonatype-nexus/templates/deployment-statefulset.yaml#L256-L259

even when the `nexusBackup.enabled` is false/disabled by default.
https://github.com/Oteemo/charts/blob/c28c76fbb53173aee9014c4b990a771a9ff5bea9/charts/sonatype-nexus/values.yaml#L145-L154

**Comment by rjkernick** [comment]
Just testing it out locally. Trying to figure out why the smoke test is failing in the PR
