### ISSUE TITLE
Unable to deploy sonarqube to air gapped cluster

### ISSUE THREAD

**Issue by codiophile** [Oteemo/charts#17]
I was trying to use this helm chart to deploy to an air gapped cluster (no internet access), but was unable to do so due to `chmod-volume-mounts` container being hard coded to use `busybox:1.31`. I need to get all images from our private repository. I had a look and it seems like this isn't the only hard coded image in the helm chart. Here's the full list:

- `chmod-volume-mounts` uses `busybox:1.31`
- `ca-certs` uses `adoptopenjdk/openjdk11:alpine`
- `test-framework` uses `dduportal/bats:0.4.0`

I think that's all of them. I got stuck on the first one and didn't test if my deployment needs the rest of them, but if we are fixing this, we should fix it for all of them regardless.

From my point of view, there are two ways to fix this. We either provide individual configuration for each of them or we can do what the `mongodb` chart does: add a `global.imageRegistry` option. The `mongodb` approach is a bigger change to implement, but easier and faster to configure for the user. It's also something that could be added later as an improvement. They should be configurable individually regardless, so we might as well start with the first approach.

I don't mind submitting a PR, as I would have to make a custom helm chart anyway. I'd just like to know what naming you'd prefer for these options. You already have `plugins.initContainerImage` and `plugins.initSysctlContainerImage`. I don't see how the latter has anything to do with the plugins, but I don't mind using that scope if that's what you'd prefer. Might be the most simplistic option. In that case, here's my proposal:

- `plugins.initVolumesContainerImage`
- `plugins.initCertsContainerImage`
- `plugins.initTestContainerImage`

Looks consistent with your existing options and the names are descriptive of what they do.

**Comment by rjkernick** [comment]
I'd be open to either one of those changes. The way mongo implements the images looks great if that is something you want to tackle. Otherwise, just adding a few extra image options will work for now.
