### ISSUE TITLE
[Nexus] - Add JAVA_TOOL_OPTIONS as env variable to nexus_proxy container

### ISSUE THREAD

**Issue by ricardojdsilva87** [Oteemo/charts#186]
Hello,
Would it be possible to add a new env variable called JAVA_TOOL_OPTIONS to the env part for nexus_proxy container on the helm chart?

The reason is this way we can manage the Java options for memory on this pod like it's done for the main nexus container.
Specs for the nexus_proxy, based on the docker image quay.io/travelaudience/docker-nexus-proxy
[https://github.com/travelaudience/nexus-proxy#environment-variables](https://github.com/travelaudience/nexus-proxy#environment-variables)

It would go something like this:

On the deployment-statefulset.yaml file
```
- name: JAVA_TOOL_OPTIONS
     value: {{ .Values.nexusProxy.env.javaOptions | quote }}
```

Example on values file would be something like:
```
- name: JAVA_TOOL_OPTIONS
     value: "-Xms3G -Xmx3G -XX:MaxDirectMemorySize=3G
```

Fir the moment I've tested adding the setting directly on the deployment and the new settings can be checked out on the pod itself using:
```
java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'
```

Thanks for your help

**Comment by KrustyHack** [comment]
Ay,

I've created a pull request for it : <https://github.com/Oteemo/charts/pull/263> :)
