### ISSUE TITLE
Unable to use corporate mirror

### ISSUE THREAD

**Issue by rcsilva83** [Oteemo/charts#20]
Hi,

In my company we use Artifactory to mirror external repositories and we have a problem to mirror Oteemo Charts repo. The problem are the "urls" tags in "index.yaml" that aren't prefixed by repo's URL ("https://oteemo.github.io/charts") but by "https://github.com/Oteemo/charts/releases/download/". As a result, the Helm Client tries to download from https://github.com/Oteemo/charts/releases/download/, which fails because the corporate proxy blocks it.

An example of a repo that is working fine is "https://kubernetes-charts.storage.googleapis.com/". All "urls" tags in "index.yaml" are prefixed by "https://kubernetes-charts.storage.googleapis.com/" (eg. https://kubernetes-charts.storage.googleapis.com/acs-engine-autoscaler-2.2.1.tgz) and Artifactory sucessfully rewrites it to our Artifactory's URL (eg. https://internal.artifactory/acs-engine-autoscaler-2.2.1.tgz).

Would it be possible to move the Charts "tgz" files to "https://oteemo.github.io/charts" (eg. https://oteemo.github.io/charts/sonarqube-4.2.0.tgz)?

Regards,

Rodrigo

**Comment by rjkernick** [comment]
Unfortunately we are taking advantage of using github releases to store the chart tgz files. We are simply using github pages to host the index file. Any way to put in a request for an exception for your artifactory server?

**Comment by rcsilva83** [comment]
I think it isn't possible...

**Comment by rjkernick** [comment]
At this time. I am not going to implement this change. Seems like a temporary workaround until your corp firewall blocks github.io as well.
