### ISSUE TITLE
Exception in thread "main" org.sonar.process.MessageException: Unsupported JDBC driver provider: mysql

### ISSUE THREAD

**Issue by tguerena** [Oteemo/charts#22]
Trying to spin up a Sonarqube instance and connect to external mysql db, and running into this error message.  Wondering if this is related to the proxy issue?  I am also behind a corporate proxy.

```Exception in thread "main" org.sonar.process.MessageException: Unsupported JDBC driver provider: mysql```

values.yaml:
```
database:
  type: "mysql"
postgresql:
  enabled: false
mysql:
  enabled: false
  mysqlUser: "redacted"
  mysqlServer: "redacted"
  mysqlPassword: "redacted"
  mysqlDatabase: "sonar"
  service:
    port: 3306```

**Comment by Cutux** [comment]
Hi! I was having the same issue and after searching a little I found that SonarQube 7.9 and above doesn't support MySQL anymore.

[SonarQube release notes](https://docs.sonarqube.org/latest/setup/upgrade-notes/)
```
Release 7.9 LTS Upgrade Notes
Upgrade can fail on Microsoft SQL Server
Migration from SonarQube v6.7.x to v7.9 fails on Microsoft SQL Server (SONAR-12260).

MySQL No Longer Supported
SonarQube no longer supports MySQL. To migrate from MySQL to a supported database, see the free MySQL Migrator tool.
```

Regards.

**Comment by rjkernick** [comment]
Thanks for the update. I'll add a note and remove the option from the chart.
