### ISSUE TITLE
[SONARQUBE] Plugins randomly disappear since chart 9.x

### ISSUE THREAD

**Issue by Guimove** [Oteemo/charts#229]
Hello,
I’ve any issue since I’ve applied the chart 9.1.x (I can’t say if 9.1.1 or 9.1.2 because they were applied in the same day).

Randomly, I was unable to find any log, all my plugins disappear from my server. I’m mandatory to run manually the script install-plugins and restart my server.

Do you have any clue? Or someone having the same issue? 

Thanks in advance

**Comment by Mikaciu** [comment]
Hello, 

I'm having the same issue when deploying on a Kubernetes cluster ; unable as well to find out the root cause, I wonder if this would be linked with the app being evicted from a pod.

**Comment by Guimove** [comment]
Yes, you are right for the cause. It seems that when the plugins are installed by Sonarqube, they are removed from the download folder, then when the pod is evicted from the node, the init script (aka install_plugins) is not relaunched so the plugins are no more presents.

**Comment by Guimove** [comment]
Hello, 

Did someone find any hint of solution to resolve that issue ?

**Comment by jabdoa2** [comment]
just install plugins via the helm chart instead of over the GUI

**Comment by Guimove** [comment]
This is what we are already doing, here is part of my values.yml
```
plugins:
  install:
      - "https://github.com/sbaudoin/sonar-yaml/releases/download/v1.5.2/sonar-yaml-plugin-1.5.2.jar"
      - "https://github.com/willemsrb/sonar-issueresolver-plugin/releases/download/sonar-issueresolver-plugin-1.0.2/sonar-issueresolver-plugin-1.0.2.jar"
      - "https://github.com/InfoSec812/sonar-auth-google/releases/download/untagged-b38ce896a2ef581af1ee/sonar-auth-googleoauth-plugin-1.6.4-SNAPSHOT.jar"
      - "https://github.com/sbaudoin/sonar-ansible/releases/download/v2.4.0/sonar-ansible-plugin-2.4.0.jar"
      - "https://github.com/checkstyle/sonar-checkstyle/releases/download/8.37/checkstyle-sonar-plugin-8.37.jar"
      - "https://github.com/kwoding/sonar-webdriver-plugin/releases/download/sonar-webdriver-plugin-1.0.7/sonar-webdriver-plugin-1.0.7.jar"
      - "https://github.com/sleroy/sonar-slack-notifier-plugin/releases/download/8.0.0-beta/sonar-slack-notifier-8.0.0-beta.jar"
      - "https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.6/sonar-dependency-check-plugin-2.0.6.jar"
      - "https://github.com/sbaudoin/sonar-shellcheck/releases/download/v2.3.0/sonar-shellcheck-plugin-2.3.0.jar"
      - "https://oss.sonatype.org/service/local/repositories/releases/content/com/hack23/sonar/sonar-cloudformation-plugin/2.0.7/sonar-cloudformation-plugin-2.0.7.jar"
      - "https://repo.maven.apache.org/maven2/com/github/spotbugs/sonar-findbugs-plugin/4.0.1/sonar-findbugs-plugin-4.0.1.jar"
```

**Comment by josefschabasser** [comment]
Hi!

We are using `kured` on our development cluster. Every time the node running Sonarqube gets rebooted, the plugins go missing. I have to manually delete the pod, then the init containers do their magic and everything is fine.
We define all the plugins using the helm chart values.

Best regards

**Comment by Guimove** [comment]
Actually my workaround is to manually run the install plugin script and reboot the pod, I found this quicker than deleting the pod.

**Comment by tigran-a** [comment]
The problem is that the plugin directory is not mounted as a part of a persistent storage. That's why after each pod restart, it gets empty.  Here is a small patch https://github.com/Oteemo/charts/pull/245/commits/601b04b85d0ccd39ebfb341985184ebf10c6506e  If it's not merged, one can always do helm pull and apply this modification...

**Comment by tigran-a** [comment]
I guess this issue can be closed?

**Comment by Guimove** [comment]
Thanks you @tigran-a
