### ISSUE TITLE
[charts/sonatype-nexus] how to add plugin

### ISSUE THREAD

**Issue by Hokwang** [Oteemo/charts#23]
Hi,

I have several question/problem about nexus.
I will create issue seperately.

Can you provide some guide to add plugin?

For example, https://github.com/sonatype-nexus-community/nexus-repository-conan
and https://github.com/flytreeleft/nexus3-keycloak-plugin.

Thanks,

**Comment by rjkernick** [comment]
You have to do it through the UI after nexus is running at this time. There is nothing built into the chart to help at this time.

**Comment by Hokwang** [comment]
@rjkernick yeah, I know there's no feature at this time,
but please think this is feature request, so please re-open and and add some code for this.
What do you think about this?

**Comment by elielam** [comment]
@rjkernick What do you mean by trought the UI ? There is no plugins console in administration.
