### ISSUE TITLE
charts/sonarqube: uses deprecated PostgreSQL Chart

### ISSUE THREAD

**Issue by alex1989hu** [Oteemo/charts#33]
**ISSUE:**
Sonarqube depends on [deprecated](https://github.com/helm/charts/pull/21408) PostgreSQL Chart 
https://github.com/Oteemo/charts/blob/a91016dac868ea589afa736e01e1f87a902a7949/charts/sonarqube/requirements.yaml#L1-L5

**Comment by rjkernick** [comment]
I'll work on moving over to: https://hub.helm.sh/charts/bitnami/postgresql

**Comment by rjkernick** [comment]
Fixed in #67
