### ISSUE TITLE
[sonarqube] the init-sysctl container should only raise vm.max_map_count

### ISSUE THREAD

**Issue by bad** [Oteemo/charts#55]
The init-sysctl unconditionally sets vm.max_map_count to 262144 even if it was set higher on the host.

It should only set vm.max_map_count if it is lower than the required value:

`
--- a/charts/sonarqube/templates/deployment.yaml
+++ b/charts/sonarqube/templates/deployment.yaml
@@ -91,9 +91,9 @@ spec:
           securityContext:
             privileged: true
           command:
-          - sysctl
-          - -w
-          - vm.max_map_count=262144
+          - /bin/sh
+          - -c
+          - 'if [[ "$(sysctl -n vm.max_map_count)" -lt 262144 ]]; then sysctl -w vm.max_map_count=262144; fi'
           {{- with .Values.env }}
           env:
             {{- . | toYaml | trim | nindent 12 }}
`

**Comment by rjkernick** [comment]
Added the change

**Comment by bad** [comment]
Thanks!
