### ISSUE TITLE
sonatype-nexus chart - sonatype/nexus3 used in values.yaml and quay.io/travelaudience/docker-nexus in the docs

### ISSUE THREAD

**Issue by rgrebski** [Oteemo/charts#76]
I was going through backup-restore cycle and I noticed that documentation says that default nexus image is `quay.io/travelaudience/docker-nexus:3.19.1` while in fact `values.yaml` uses `sonatype/nexus3:3.21.2`

Should documentation or values.yaml be updated ?

**Comment by rjkernick** [comment]
Documentation needs updated. I also need to make a note that the backup functionality only works fully with the travelaudience docker image. It has a few tweaks that aren't available in the sonatype container.
