### ISSUE TITLE
Nexus: Add the ability to create a list of extra ConfigMaps

### ISSUE THREAD

**Issue by tylerauerbeck** [Oteemo/charts#79]
For folks who are using the nexus-kubernetes-openshift plugin, it would be useful to be able to specify these configmaps as part of this chart.

**Comment by tylerauerbeck** [comment]
I've got this working already, just interested in whether this would be something the team would be willing to add/support.

**Comment by rjkernick** [comment]
I'd definitely be interested. Feel free to open a PR with the changes and I'll take a look.

**Comment by guyou** [comment]
Why including support of ConfigMap directly in the Chart?
Why not simply relying on Kutomize to deploy these ConfigMaps?
