### ISSUE TITLE
[sonarqube] init container fails on certs directory

### ISSUE THREAD

**Issue by BryanHunt** [Oteemo/charts#86]
If you don't set caCerts, the init container will will fail with the log message:

```
mkdir: can't create directory '/opt/sonarqube/certs': Permission denied
```

**Comment by BryanHunt** [comment]
I read the chart wrong.  When you deploy, the init container fails independent of having set caCerts.  It appears the following is missing from the init container.

```
          - mountPath: /opt/sonarqube/temp
            name: sonarqube
            subPath: temp
```

**Comment by BryanHunt** [comment]
Oops, it should be:

```
          - mountPath: /opt/sonarqube/certs
            name: sonarqube
            subPath: certs
```

**Comment by AndrewHynes** [comment]
I've also experienced this. Thanks for providing workarounds here and in the other issue.
