### ISSUE TITLE
changes to nexus label causes pvc to be replaced

### ISSUE THREAD

**Issue by alextwlam-melco-resorts-com** [Oteemo/charts#93]
charts/charts/sonatype-nexus/templates/pvc.yaml

I was using helmfile to apply the nexus chart, sometime ago I find the night apply failed. Closer check shows it was caused by a replacment of pvc, which was in turn caused by a change in label. 

since nexus.label was added to the pvc, any changes to the nexus.label, e.g. chart name, would cause pvc to be replaced, which i don't think would be an expected behaviour: 

Failure started from 7-Apr, which i assume was caused by a bump from to 1.27.0. I am falling back to  1.26.6. 

`
 default, sonatype-nexus-data, PersistentVolumeClaim (v1) has changed:
   # Source: sonatype-nexus/templates/pvc.yaml
   kind: PersistentVolumeClaim
   apiVersion: v1
   metadata:
     name: sonatype-nexus-data
     labels:
       app: sonatype-nexus
       fullname: sonatype-nexus
 -     chart: sonatype-nexus-1.27.1
 +     chart: sonatype-nexus-2.0.0
       release: sonatype-nexus
       heritage: Helm
   spec:
     accessModes:
       - "ReadWriteOnce"
     resources:
       requests:
         storage: "8Gi"
 Upgrading release=sonatype-nexus, chart=oteemocharts/sonatype-nexus
 FAILED RELEASES:
 NAME
 sonatype-nexus
 in ./helmfile.yaml: failed processing release sonatype-nexus: helm exited with status 1:
   Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: default, name: sonatype-nexus-backup, existing_kind: /v1, Kind=PersistentVolumeClaim, new_kind: /v1, Kind=PersistentVolumeClaim
`

**Comment by rjkernick** [comment]
I'm not sure what changed to have caused that problem. Looking through the changes, I can't seem to pinpoint the issue. Feel free to take a look at this: https://github.com/Oteemo/charts/compare/sonatype-nexus-1.26.6...sonatype-nexus-2.1.0

**Comment by alextwlam-melco-resorts-com** [comment]
seems pvc.yaml hasn't changed since first release. 
i think every version change would trigger a pvc re-creation. just that i wasn't aware. sorry.

**Comment by zcrisler** [comment]
@rjkernick Seems related to this [known issue with adding the `chart` label on volumeClaimTemplates in StatefulSets](https://github.com/helm/charts/issues/7803#issuecomment-575032640).
