### ISSUE TITLE
[Sonarqube] - plugins mangement strange behavior

### ISSUE THREAD

**Issue by gabyfulchic** [Oteemo/charts#94]
**Hello everybody,**
```bash
helm version : 2
kubectl version : 1.16
sonarqube version : 8.2 developer edition
```

To deploy Sonarqube on Kubernetes, I'm using your chart because the last one is deprecated. But during my last maintainance, I was upgrading Sonarqube after building sonarqube 8.2 developer edition docker image, and i encounter a strange behavior. The upgrade was also providing a more complete plugins list. And after the upgrade, I saw that the default plugins were removed. Only my listed plugins were installed and in the `/opt/sq/extensions/plugins/tmp` folder. 

I investigated a bit. When I deploy the docker image locally, I can see that the default plugins are well installed in `extensions/plugins/*.jar`.  
So I investigated in the `copy-plugins.yaml` & `install-plugins.yaml` and just saw that same if we set the value `deleteDefaultPlugins: false`, all the default plugins are deleted because of the **both "for" loop.**

![image](https://user-images.githubusercontent.com/22600727/79774871-b0bd7b00-8333-11ea-9f38-439e785ebb18.png)

I executed in local the script with fake plugins, and we can well see that in the first loop it iterates in all the `extensions/plugins/*.jar` and the second one too. So everytime that the plugins targeted are the same, they are removed. But the both "for" loops iterates over all plugins so they will obviously match everyfile one by one. Only because of this condition : 
![image](https://user-images.githubusercontent.com/22600727/79775161-232e5b00-8334-11ea-9a1a-2ec0c304351b.png)

So to conclude, the `install-plugin.yaml` part `wget` all plugins listed in `extensions/plugins/tmp` folder & then `copy-plugins.yaml` copy them in plugins/ but without keeping the default ones same with `deleteDefaultPlugins: false`. 

**Question**
Was it wanted to use 2 plugins folder and store installed plugins in `plugins/tmp` before removing all the default plugins whatever we set in the `deleteDefaultPlugins` key ?

**Ps** 
double "for" loop output here : https://pastebin.com/NYf76dxq

**Comment by guyou** [comment]
I think it is related to #61

**Comment by gabyfulchic** [comment]
Yes It is. Sorry for the duplication 
Do you want me to close it & to follow the #61 ? :smile:

**Comment by gbonnefille** [comment]
As the #61 is closed and fixed, I suggest you to close this current issue.
