### ISSUE TITLE
Customizing postgresqlPassword

### ISSUE THREAD

**Issue by delphe** [Oteemo/charts#95]
I'd like to pass in a custom postgresql.postgresqlPassword. The documentation at https://hub.helm.sh/charts/oteemo/sonarqube has "Customizing the chart" with an old link:
https://docs.helm.sh/using_helm/#customizing-the-chart-before-installing... I found the newer link here: https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing

If I use a command like `helm install --values values.yml myNewSonarQube --set postgresql.postgresUser=mySonarUserTest,postgresql.postgresPassword=mySonarPassTest oteemo/sonarqube` or `helm upgrade --install --values values.yml myNewSonarQube --set postgresql.postgresUser=mySonarUserTest,postgresql.postgresPassword=mySonarPassTest oteemo/sonarqube` it doesn't change the default username and password for postgresql.

**Comment by rjkernick** [comment]
Thanks. Updated the docs to reflect some new links. I think your issue is some outdated docs. all fields are postgresql.postgresql. You were missing the 'ql' in a couple places. 

```
helm install ---set postgresql.postgresqlUser=mySonarUserTest,postgresql.postgresqlPassword=mySonarPassTest mySonarqube oteemo/sonarqube
```

**Comment by delphe** [comment]
@rjkernick , using postgresql.postgresqlUser=mySonarUserTest with the 'pl' doesn't seem to work either. After the install is finished I used `kubectl describe pod/mySonarqube-sonarqube-...` and showed:
> SONARQUBE_JDBC_USERNAME:  sonarUser

... does it work for you?

**Comment by delphe** [comment]
Based on this code...
```- name: SONARQUBE_JDBC_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
```
... I think I need to use postgresqlUsername instead of postgresqlUser. I'll give that a try.

**Comment by delphe** [comment]
Yep, using postgresqlUsername worked. I also updated the password using postgresqlPassword. Thanks for your help, @rjkernick !
