### ISSUE TITLE
[SONARQUBE] Getting "CreateContainerConfigError" error with pod initialization with postgresql

### ISSUE THREAD

**Issue by smartlizzard** [Oteemo/charts#97]
I am getting error for pod initialization.

Error: secret "sonarqube-postgresql" not found

Deploying steps:
$ helm install sonarqube oteemocharts/sonarqube -f values.yaml
This values.yaml is provided in this repo

**Comment by n2aws** [comment]
@smartlizzard  My guess is that you've modified the values.yaml file?  The default file has the postqresql secret commented out. Your error seems to indicate you've told it to use a secret.

Have a look at this setting:  https://github.com/Oteemo/charts/blob/master/charts/sonarqube/values.yaml#L205

I you intended to use a secret, then you'll need to manually create it in the namespace.  If not, you likely need to comment that line out, and provide the credentials via the other postgresql* settings.

**Comment by smartlizzard** [comment]
Hi,

Thanks for your reply.
